services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/etc:/etc/grafana:ro
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=uwfe
      - GF_SECURITY_ADMIN_PASSWORD=uwfepassword
      - DOCKER_INFLUXDB_INIT_ORG=uwfe
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=secrettoken

  monitor:
    build: ./monitor
    container_name: uwfe_monitor
    restart: always
    # networks:
    #   - tcp-network

  test-server:
    build: ./test-server
    container_name: uwfe_test_tcp_server
    ports:
      - "12345:12345"
    restart: always
    # networks:
    #   - tcp-network

  influxdb:
    image: influxdb:2-alpine
    volumes:
      - influxdbv2:/.influxdbv2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=uwfe
      - DOCKER_INFLUXDB_INIT_PASSWORD=uwfepassword
      - DOCKER_INFLUXDB_INIT_ORG=uwfe
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=secrettoken
      - INFLUXDB_HTTP_HTTPS_ENABLED=true

    ports:
      - "8086:8086"

volumes:
  influxdbv2:
  grafana-storage:
# networks:
#   tcp-network:
#     driver: bridge
