{
 "title": "UWFE - Prototype",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "DTC's Received",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: -1h) // Adjust the time range as needed\r\n  |> filter(fn: (r) => \r\n      r[\"signal_name\"] == \"DTC_CODE\"\r\n    )\r\n  |> count()"
    }
   ]
  },
  {
   "title": "Cell Temps Min and Max",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"signal_name\"] == \"TempCellMin\" or r[\"signal_name\"] == \"TempCellMax\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "LV Bus Current",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"LV_Bus_Measurements\")\r\n  |> filter(fn: (r) => r[\"signal_name\"] == \"CurrentBusLV\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Motor Speeds",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SpeedFeedbackLeft\" or r[\"_measurement\"] == \"SpeedFeedbackRight\")\r\n  |> filter(fn: (r) => r[\"signal_name\"] == \"SpeedMotorRight\" or r[\"signal_name\"] == \"SpeedMotorLeft\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"VCU_Data\")\r\n  |> filter(fn: (r) => r[\"signal_name\"] == \"ThrottlePercent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Throttle and Brake Percent",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 12, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"VCU_Data\")\r\n  |> filter(fn: (r) => r[\"signal_name\"] == \"BrakePercent\" or r[\"signal_name\"] == \"ThrottlePercent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cell Temps (C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BMU_ChannelTemp\")\r\n  |> filter(fn: (r) => r[\"signal_name\"] != \"TempChannelMuxSelect\")\r\n  |> filter(fn: (r) => r[\"signal_name\"] != \"TempChannel69\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  }
 ]
}